### ISSUE TITLE
function set up problem

### ISSUE THREAD

**Issue by ShukhratSh** [sixy6e/image_processing#1]
Hi,
I am having a following issue in setting up image-processing tools in supercomputer. 
"image-processing]$ python setup.py install --user
running install
running build
running build_py
running install_lib
byte-compiling /home/147/ss8137/.digitalearthau/20171214/local/lib/python3.6/site-packages/image_processing/segmentation.py to segmentation.cpython-36.pyc
Sorry: TabError: inconsistent use of tabs and spaces in indentation (segmentation.py, line 1077)
byte-compiling /home/147/ss8137/.digitalearthau/20171214/local/lib/python3.6/site-packages/image_processing/thresholding.py to thresholding.cpython-36.pyc
  File "/home/147/ss8137/.digitalearthau/20171214/local/lib/python3.6/site-packages/image_processing/thresholding.py", line 84
    print 'No input image!!!'
                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'No input image!!!')?

running install_egg_info
Removing /home/147/ss8137/.digitalearthau/20171214/local/lib/python3.6/site-packages/image_processing-0.6.1-py3.6.egg-info
Writing /home/147/ss8137/.digitalearthau/20171214/local/lib/python3.6/site-packages/image_processing-0.6.1-py3.6.egg-info
"
Am I doing something wrong? Please let me know.

Thanks,

**Comment by sixy6e** [comment]
No, you haven't done anything wrong.  I just haven't got around to updating this package to Python 3.  I'll put a fix in now.

**Comment by sixy6e** [comment]
Updated, and good timing too.  I have some work coming up that needs requires this module.  Thanks for the notification!!!

**Comment by ShukhratSh** [comment]
Thanks Josh!


Best regards,
Shukhrat

**Comment by ShukhratSh** [comment]
Hi Josh,

I think I didn't mention in the post that I use Anaconda for Python 3,
which may require additional update. I updated PDAL using " conda install
-c mathieu pdal ". However, it is running endless like before (3 hours
already).
Is there anything I should do to get your updated PDAL?

Thank you very much!


Best regards,
Shukhrat

**Comment by sixy6e** [comment]
You might want to check with the folks that maintain PDAL (Point Data Abstraction Library).  I can't imagine that PDAL would require 3 hours to download and install (unless a really bad internet connection, or a proxy that needs to be proxy).

**Comment by ShukhratSh** [comment]
Hi Josh,

Sorry about my previous email, I think I wasn't clear enough. I updated
PDAL successfully, there is not problem with that. However, noise filter
script is running endless like before after your update.
Can you help me with sorting it out?
Thank,





Best regards,
Shukhrat
